#author: Sarah McCarthy 
#date created: 9/13/2021
#given DNA string and returns count of nucleotides A C G T
#rosalind DNA

#input string of DNA nucleotides 
#in_DNA = 'AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC'
in_DNA = 'ACCATGTGGGCGCGGAGCACTGGAGACGGTTGATCGTTTGGTCCGGGACTGCATTTCACCCAGATCATGATTGTGTGTTGTGGTGTTCACTGCGAATTGGTAGCTGAGATACGCTTTCGACGGGCAAGTACCTGTTGTCACCCCTGATCGAGATCGTCCCAGTATTCTAAGCGGACCCTGAAATATTTGTAGCAGAGGCTCTCCTTGCGCTGACAACAATTTGCTATCCAATAAGTTCTCTCGTGAATCTGTACTTACGACACACGCGGTGGACGATATTCAAATCTGTGAGAGTGGGGCAAGAACACTGTGTTCGCCACCGAGTCTGAGAAAATTGGACAAAATACATGAGATAAGATGGGTAGTAGCTGCGTACCAAGCATCGTTTTGATCTCGATAATAATCAGTCGGGTAGCATAAATAAAAGAGGCATCGTACACAGAGCGCCTAAGAATTGCCGTCGCTGTAGTGGTACATGAAGATTTTAATTTTTGGCGACCGTGCGTATAAAAATTAACCTTTTAGAACTCAGTTTGTAACCAACCACAAATTCCAGATTGCGGCGTCGAGGAAAAAAGTGCCAAGCAATATTAGATAATTTAACTGATTATCCCGTAACGTGGGTCTAGAGAGTTCAAGGTGATCTCCTGCGCGGCATCAATGATATCCCGTTATCTGGGGATAGGAGTGTAGCTCTCTTGTATAGTAACTAGGTGATTTGACTATCCGTAGCCAGTATAAACCCGCCAGTGTATAGTACCACGTGACAGACCGGGGCACTGTGCGAAAATAATGTGTGAGAGATCCAACTCATAGCCCGACGTCCTAC'
#variables for keeping track of counts for each nucleotide 
count_A = 0
count_C = 0
count_G = 0
count_T = 0

#loop through DNA string char by char
#if char matches nucleotide, increase count
for nucleotide in in_DNA:
    if nucleotide == 'A':
        count_A +=1
    elif nucleotide == 'C':
        count_C +=1
    elif nucleotide == 'G':
        count_G +=1
    elif nucleotide == 'T':
        count_T +=1
    else:
        print('error: not a valid nucleotide')

#print answer in A C G T 
print(str(count_A) + ' ' + str(count_C) + ' ' + str(count_G) + ' ' + str(count_T))