#author: Sarah McCarthy 
#date created: 9/13/2021
#takes in DNA string and prints reverse complement 
#rosalind REVC

#input DNA string 
#in_DNA = 'AAAACCCGGT'
in_DNA = 'TACTCCTTCAACCGCAGAGAACCTCAAGCGAGTGCAGTCGACATACTGCTACCCACTGGACCTTACGAGCATTCCATGATAAGGTCTATGGCGACGAGCAAGTAAGTCGCGGCTTTGAATTCGGTTCGGGACCATATACGCTGGGTACGTAAGAAGTCTCACCATGGTCCGTTATTGATGGTGACGTGTGTGTTTCTGCCGGGACTCGCTTGGCTGGGACATTCAGCGGACTGTGACCGATAATACCTCATGCTCCAAAATATCCGGCACGAAGAAGCGAGGTTGTCTATATCTTTATGGGCTGGTCAGACTTGCTACCTGCCCTCCGCGCCGCGGGACAGGCGTCGTCCTTAATGCTTAGGATAATACCCGAACATTTCCCAAACCATGAACTATCGTAGGGCGCAATGCTATAGCATGCGGCACCCCCCGATATAGGACGAATTAATTCCGCATGTGCTATAGCGGAACTGGCTCCGCTCATACCCCAAGCTACACTCGCCTCATAACATATACATGAGTTCCCTGATGCTAAAGTGTTGTGTAGAATATGCTCTAGTGGGTAGAGCAGACTCTTGCGTTCCGCCTAGTCTACTACACCGCATTATCTCACCTCTTAGTATAAGAGCAGCTATATGTCATCGACTGAGGCTTTCCATCAAAGCTTTGGTAGATAATTCTCCAAGCTAGGATCCAAGGACGTGACGTGTCGCCCCCCCAGAACTTGTTAAGCATCAGTCTTATATAACTCGCGCAGATAATGCGGCTAGTAATGATATTCTTGTTACTTGAGTGCAGAAGGTACATCATG'
#string for output 
out_DNA = ''

#go through input DNA string
#assign nucloetide to out_DNA string based on in_DNA base 
for nucleotide in in_DNA:
    if nucleotide == 'A':
        out_DNA = 'T' + out_DNA
    elif nucleotide == 'C':
        out_DNA = 'G' + out_DNA
    elif nucleotide == 'G':
        out_DNA = 'C' + out_DNA
    elif nucleotide == 'T':
        out_DNA = 'A' + out_DNA
    else:
        print('error not a valid nucleotide input')

#print out the answer 
print(out_DNA)