# author: Sarah McCarthy
# date created: 09/21/2021
# takes in two strings s and t, t is a substring of s, return the locations at which t appears in s
# rosalind SUBS

#input strings 
s = 'TCCGGGCTACCAATTCCGGGCAATCCGGGCTCCGGGCTAACTCCGGGCCTCCGGGCATTCGGTTTCCGGGCTCCGGGCTCCGGGCTCATCCGGGCTCCGGGCGATCTTCCGGGCTCCGGGCTCCGGGCGTCCGGGCTCTAGGCACGTCCGGGCTCCGGGCTTTTATCCGGGCTTGTCCGGGCTTCCGGGCTCCGGGCTCCGGGCTCCGGGCCGAAGTCCGGGCAATGAATTCCGGGCGTCCGGGCTCCGGGCGTGGATCCGGGCTCCGGGCATCCGGGCTCCGGGCTTTTCTCTCCTCCGGGCTCCGGGCCGTCCGGGCTCCGGGCGCTCCGGGCATCCGGGCATCCGGGCGCTATGCTCCGGGCTGCTCAGTCCGGGCGGTGTCCGGGCGATTCCGGGCATCCGGGCTTCCGGGCCGTGTCCGGGCTCCGGGCGATTCCGGGCTTTCCGGGCATTAGTTCCGGGCTCCGGGCTTTCTCCGGGCTCCGGGCCATCCGGGCGCTCCGGGCGTGTCCGGGCGTCCGGGCTCCGGGCGCTCCGGGCTCTCCGGGCTGGTCCGGGCCGGTCCGGGCTCCGGGCAGTCCGGGCGATCTCCGGGCTCCGGGCGCCGTCCGGGCGTCCGGGCTATTCCGGGCTCCGGGCTCCGGGCTTGAAACTCCGGGCTCCGGGCTTTACATCCGGGCATATCCGGGCCGCGGCCCAACAGCTTCCGGGCTCCGATGTCTGAGTCCGGGCATCCGGGCTCCGGGCTCCGGGCTCCGGGCTAATTCCGGGCCACTGACAGTCCGGGCTCCGGGCTCCGGGCTTGTTCTCCGGGCTCCGGGCAGTCCGGGCTCCGGGCCCTGCTCCGGGCGTCCGGGCTCCTCCGGGC'
t = 'TCCGGGCTC'
length_t = len(t)
#list for keeping track locations at which motifs occur
locations = []

#go through string char by char+length of motif
print(len(s))
for location in range(len(s)):
    if s[location:(location+length_t)] == t:
        locations.append(location+1)

#print result
if not locations:
    print('no motifs found')
else:
    for x in locations:
        print(x)
